[project]
authors = ["knmcguire <kimberleymcguire@gmail.com>"]
channels = ["conda-forge"]
name = "aerial_robotic_landscape"
platforms = ["win-64", "osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"

[pypi-dependencies]
mkdocs = "~=1.6.1"
pymdown-extensions = "~=10.12"
mkdocs-git-revision-date-localized-plugin = "~=1.3.0"
mkdocs-linkcheck = "~=1.0.6"
requests = "~=2.32.3"
mkdocs-embed-external-markdown = ">=3.0.2, <4"
mdx-include = ">=1.4.2, <2"
mkdocs-include-markdown-plugin = ">=7.1.7, <8"
